//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechParamsCalc.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TechCalc")]
        public string SQLDataBase {
            get {
                return ((string)(this["SQLDataBase"]));
            }
            set {
                this["SQLDataBase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TechCalc")]
        public string SQLServerDataBase {
            get {
                return ((string)(this["SQLServerDataBase"]));
            }
            set {
                this["SQLServerDataBase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Al")]
        public string SQLServerLogin {
            get {
                return ((string)(this["SQLServerLogin"]));
            }
            set {
                this["SQLServerLogin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("kip12")]
        public string SQLServerPassword {
            get {
                return ((string)(this["SQLServerPassword"]));
            }
            set {
                this["SQLServerPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5432")]
        public string SQLServerPort {
            get {
                return ((string)(this["SQLServerPort"]));
            }
            set {
                this["SQLServerPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SchneiderElectric.SCADA.OpcDaServer.1\\")]
        public string OPCServerName {
            get {
                return ((string)(this["OPCServerName"]));
            }
            set {
                this["OPCServerName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OPCServerSubString {
            get {
                return ((string)(this["OPCServerSubString"]));
            }
            set {
                this["OPCServerSubString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("S08_01_W01_LT01")]
        public string AtmoPressureTag {
            get {
                return ((string)(this["AtmoPressureTag"]));
            }
            set {
                this["AtmoPressureTag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10.12.70.16")]
        public string SQLServerAddress {
            get {
                return ((string)(this["SQLServerAddress"]));
            }
            set {
                this["SQLServerAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("S08_01_W03_LT01,S08_01_W04_LT01")]
        public string OtherTagsFromOPC {
            get {
                return ((string)(this["OtherTagsFromOPC"]));
            }
            set {
                this["OtherTagsFromOPC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EXTERNAL_EXCHANGE")]
        public string ServerSyncWryteTag {
            get {
                return ((string)(this["ServerSyncWryteTag"]));
            }
            set {
                this["ServerSyncWryteTag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EXTERNAL_EXCHANGE")]
        public string ServerSyncWriteTag {
            get {
                return ((string)(this["ServerSyncWriteTag"]));
            }
            set {
                this["ServerSyncWriteTag"] = value;
            }
        }
    }
}
